# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 830a2571ee6d7019a939f62ff71eddb3c0d68ca5379de10f1430f64f21fde65d3a511e611055bc5151b2d1e3bcccbcdb1fbe50fc0e6a408745f81907de7f8bb0

test:
  secret_key_base: 26cf98e3830947f51d76e3c7a6f6c6de1c9e186964a1af492ba301790f52a3a1d81e92f981d898c9dd65b31b307ac0bd474a39c09941f627306a33b82e2d98ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
